ignore:
  - node_modules/**
  - site/**
  - .venv/**
rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: whatever
  truthy:
    check-keys: false
  trailing-spaces: enable
