openapi: 3.1.0
info:
  title: Circl Public API
  version: 0.1.0
servers:
  - url: https://api.circl.dev

paths:
  /search:
    get:
      summary: Search for products and places
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: lat
          schema:
            type: number
        - in: query
          name: lng
          schema:
            type: number
      responses:
        '200':
          description: OK

  /products/{id}:
    get:
      summary: Get a product by id
      description: Returns a universal product resource for the given ID (e.g., barcode).
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product identifier (e.g., barcode)
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: ../schemas/universal/product.json
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                required: [error, message]
                properties:
                  error:
                    type: string
                  message:
                    type: string

