openapi: 3.0.3
info:
  title: CIRCL API
  version: 0.1.0
  description: >
    APIs for search and product retrieval, returning the **Universal Product** schema.
  contact:
    name: CIRCL Team
    url: https://github.com/andremair97/circl-docs
    email: andremair@hotmail.co.uk

servers:
  - url: https://api.example.com
    description: Production (placeholder)

tags:
  - name: Search
    description: Search endpoints
  - name: Products
    description: Product retrieval and details

paths:
  /search:
    get:
      tags: [Search]
      operationId: searchProducts
      summary: Search for products
      description: Returns search results for products matching the given query.
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string, minLength: 1 }
          description: Search query string
        - in: query
          name: lat
          schema: { type: number }
          description: Latitude coordinate
        - in: query
          name: lng
          schema: { type: number }
          description: Longitude coordinate
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
                    minimum: 0
                required: [items, total]

  /products/{id}:
    get:
      tags: [Products]
      operationId: getProductById
      summary: Get a product by ID
      description: Retrieve a single product mapped into the universal schema.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
          description: Product identifier or barcode
      responses:
        '200':
          description: A universal product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

components:
  schemas:
    Product:
      # External file reference — note the path is relative to THIS file's location (openapi/)
      $ref: ../schemas/universal/product.schema.json

