name: Cross-Platform CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: "pnpm build --filter web..."
      - run: "pnpm test --filter web..."

  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: EAS Build (if token)
        run: |
          if [ -n "$EAS_TOKEN" ]; then
            npx eas build --platform android --non-interactive
          else
            echo 'Skipping EAS build; no token'
          fi
