name: release-compile-changelog

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build changelog
        run: python scripts/build_changelog.py
      - name: Commit and push
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo 'No fragments to compile'
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add PROJECT_CHANGELOG.md changelog || true
          git commit -m "chore(changelog): compile fragments"
          git push
