name: release-compile-changelog

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Compile changelog
        run: RUN_MODE=write python scripts/compile_changelog.py
      - name: Commit and push
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          if git commit -m "chore: compile changelog"; then
            git push
          else
            echo "No changes to commit"
          fi
