name: require changelog fragment
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited, labeled]
permissions:
  contents: read
  pull-requests: read
jobs:
  check-fragment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Skip if label present
        if: contains(join(fromJson('["' + join(github.event.pull_request.labels.*.name, '","') + '"]'), ','), 'skip-changelog')
        run: echo "skip-changelog label present — bypassing." && exit 0
      - name: Ensure a fragment exists under /changelog/
        run: |
          set -euo pipefail
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          if git diff --name-only "$base" "$head" | grep -E '^changelog/.*\.md$' >/dev/null; then
            echo "Fragment found ✅"
          else
            echo "::error ::Add a fragment under /changelog/ (or apply the 'skip-changelog' label)."
            exit 1
          fi
